spring:
  application:
    name: login
  data:
    mongodb:
      uri: mongodb://localhost:27017/login_db
    redis:
      host: localhost
      port: 6379
logging:
  level:
    com.will1523.login: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
